import assets from "@/assets";

export const explore = [
  { name: "Podcasts", img: assets.images.search[1] },
  { name: "Live Events", img: assets.images.search[2] },
  { name: "Made For You", img: assets.images.search[3] },
  { name: "New releases", img: assets.images.search[4] },
  { name: "Brazil", img: assets.images.search[5] },
  { name: "Sertanejo", img: assets.images.search[6] },
  { name: "Brazilian Funk", img: assets.images.search[7] },
  { name: "Pop", img: assets.images.search[8] },
  { name: "Charts", img: assets.images.search[9] },
  { name: "Hip-Hop", img: assets.images.search[10] },
  { name: "Samba & Pagode", img: assets.images.search[11] },
  { name: "MPB", img: assets.images.search[12] },
  { name: "AMPLIFIKA", img: assets.images.search[13] },
  { name: "Discover", img: assets.images.search[14] },
  { name: "Dance/Electronic", img: assets.images.search[15] },
  { name: "Christian & Gospel", img: assets.images.search[16] },
  { name: "Rock", img: assets.images.search[17] },
  { name: "Indie", img: assets.images.search[18] },
  { name: "RADAR", img: assets.images.search[19] },
  { name: "GLOW", img: assets.images.search[20] },
  { name: "EQUAL", img: assets.images.search[21] },
  { name: "Fresh Finds", img: assets.images.search[22] },
  { name: "Mood", img: assets.images.search[23] },
  { name: "Workout", img: assets.images.search[24] },
  { name: "Chill", img: assets.images.search[25] },
  { name: "Party", img: assets.images.search[26] },
  { name: "At Home", img: assets.images.search[27] },
  { name: "In the car", img: assets.images.search[28] },
  { name: "Sleep", img: assets.images.search[29] },
  { name: "Love", img: assets.images.search[30] },
  { name: "Cooking & Dining", img: assets.images.search[31] },
  { name: "Wellness", img: assets.images.search[32] },
  { name: "Focus", img: assets.images.search[33] },
  { name: "Trending", img: assets.images.search[34] },
  { name: "Decades", img: assets.images.search[35] },
  { name: "Spotify Singles", img: assets.images.search[36] },
  { name: "Cities", img: assets.images.search[37] },
  { name: "Travel", img: assets.images.search[38] },
  { name: "Summer", img: assets.images.search[39] },
  { name: "Latin", img: assets.images.search[40] },
  { name: "R&B", img: assets.images.search[41] },
  { name: "K-pop", img: assets.images.search[42] },
  { name: "Songwriters", img: assets.images.search[43] },
  { name: "Music + Talk", img: assets.images.search[44] },
  { name: "Kids & Family", img: assets.images.search[45] },
  { name: "TV & Movies", img: assets.images.search[46] },
  { name: "Gaming", img: assets.images.search[47] },
  { name: "Anime", img: assets.images.search[48] },
  { name: "Tastemakers", img: assets.images.search[49] },
  { name: "Netflix", img: assets.images.search[50] },
  { name: "Student", img: assets.images.search[51] },
  { name: "League of Legends", img: assets.images.search[52] },
  { name: "Reggae", img: assets.images.search[53] },
  { name: "Caribbean", img: assets.images.search[54] },
  { name: "Afro", img: assets.images.search[55] },
  { name: "Arab", img: assets.images.search[56] },
  {
    name: "Asian Pacific Islander Heritage Month",
    img: assets.images.search[57],
  },
  { name: "Happy Holidays", img: assets.images.search[58] },
  { name: "Classical", img: assets.images.search[59] },
  { name: "Instrumental", img: assets.images.search[60] },
  { name: "Jazz", img: assets.images.search[61] },
  { name: "Folk & Acoustic", img: assets.images.search[62] },
  { name: "Soul", img: assets.images.search[63] },
  { name: "Metal", img: assets.images.search[64] },
  { name: "Punk", img: assets.images.search[65] },
  { name: "Blues", img: assets.images.search[66] },
  { name: "Funk & Disco", img: assets.images.search[67] },
  { name: "Ambient", img: assets.images.search[68] },
  { name: "Alternative", img: assets.images.search[69] },
  { name: "Country", img: assets.images.search[70] },
];
